# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
#commented by Jitendra from given below

default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
#commented by Jitendra from given above

development:
  adapter: mysql
  encoding: utf8
  database: resume
  pool: 5
  username: root
  password: root

test:
  adapter: mysql
  encoding: utf8
  database: resumedevelopment
  pool: 5
  username: root
  password: root

production:
  adapter: mysql
  encoding: utf8
  database: resumedevelopment
  pool: 5
  username: root
  password: root