# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 586935b7962035d194127b0e07ff6846142ac43058bcd6ccb48e9adbf97a793d52a363b01ca063ed3d1a9c1726d856b1b19fce6ac1a04ba7a7c2c8cdbc00ffde

test:
  secret_key_base: 0dd64d11df5d5bfa7766c076cb6ec6e723eb58d28a925a6e14e80c1018f1b78cf018b0d1c374be9c7c542c47916adec36d533890ded2b821b6689fbb81912cdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
